name: Build and Release Windows App

on:
  workflow_dispatch:
  release:
    types:
      - created # 在创建新的 Release 时触发

jobs:
  build-windows:
    runs-on: windows-latest # 在最新的 Windows 环境上运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # 你项目使用的 Node.js 版本

      - name: Install dependencies
        run: npm ci # 使用 npm ci 以确保干净安装

      - name: Build Electron App
        run: npm run build # 运行 package.json 中定义的 build 脚本
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 