name: Build and Release Windows App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签时触发
  release:
    types:
      - created # 在创建新的 Release 时触发

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest # 在最新的 Windows 环境上运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录，以便 standard-version 可以生成 changelog

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # 你项目使用的 Node.js 版本

      - name: Install dependencies
        run: npm ci # 使用 npm ci 以确保干净安装

      - name: Get version
        id: get-version
        run: |
          $PACKAGE_VERSION = node -p "require('./package.json').version"
          echo "version=$PACKAGE_VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Build Electron App
        run: npm run build # 运行 package.json 中定义的 build 脚本
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload build artifact (Manual Trigger)
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: idok-windows-build
          path: dist/*.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.2
        if: github.ref_type == 'tag'
        with:
          name: idok v${{ steps.get-version.outputs.version }} 发布
          body_path: CHANGELOG.md
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}